# ─────────────────────────────────────────────────────────────────────────────
#  word_lists.py  –  all vocabulary for the idea generator
# ─────────────────────────────────────────────────────────────────────────────

# ── Adjectives ────────────────────────────────────────────────────────────────
adjectives = [
    # Technical descriptors
    "Automated", "Intelligent", "Lightweight", "Scalable", "Modular",
    "Collaborative", "Decentralized", "Adaptive", "Minimal", "Robust",
    "Interactive", "Offline-first", "Privacy-focused", "Real-time", "Cross-platform",
    "Flexible", "Customizable", "Efficient", "Synchronous", "Asynchronous",
    "Responsive", "Cloud-native", "Secure", "Portable", "Dynamic",
    "Smart", "Streamlined", "Versioned", "Composable", "Intuitive",
    "Transparent", "Fast-loading", "Low-latency", "Resilient", "Event-driven",
    "Predictive", "Self-healing", "Battery-friendly", "Lightweight-optimized", "User-centric",
    "Declarative", "Testable", "Configurable", "Plug-and-play", "Extensible",
    "Error-tolerant", "AI-powered", "Graphical", "Command-line-friendly", "Modularized",
    "Network-aware", "Stateless", "High-availability", "SaaS-ready", "Cross-device-compatible",
    "Zero-config", "Schema-driven", "Type-safe", "Fault-tolerant", "Headless",
    "Immutable", "Reactive", "Pipeline-oriented", "Multi-tenant", "Edge-optimized",
    "Containerized", "Observable", "Idempotent", "Concurrency-safe", "Role-based",
    "Self-documenting", "Audit-ready", "Context-aware", "Token-efficient", "Serverless-first",
    "Human-readable", "Memory-safe", "Dependency-free", "Schema-less", "Batch-optimized",
    "Zero-downtime", "Cache-friendly", "Interrupt-driven",
    # Humorous
    "Overly-caffeinated", "Haunted", "Passive-aggressive", "Crypto-bro-approved",
    "Technically-on-fire", "Sentient-adjacent", "Disturbingly-fast", "Aggressively-opinionated",
    "Unnecessarily-recursive", "Deeply-apologetic", "Chronically-online", "Vibes-based",
    "Gaslit-by-design", "Suspiciously-eager", "Post-agile", "Legally-distinct",
    "Emotionally-unavailable", "Governance-averse", "Probabilistically-correct", "Galaxy-brained",
    "Caffeine-dependent", "Duct-tape-and-dreams", "Load-bearing", "Cursed-but-functional",
    "AI-guilty", "Shamefully-imperative", "Revenge-tested", "Accidentally-sentient",
    # Scientific / aerospace
    "Orbital", "Cryogenic", "Suborbital", "Exoatmospheric",
    "Telemetric", "Swarm-capable", "Laser-guided", "Seismic-aware", "Biocompatible", "Isotope-tagged", "Tidal-locked",
    "Deep-space-rated", "Self-replicating", "Molecular-scale",
    "Computationally-irreducible", "Petabyte-scale", "Nanosecond-precise", "Exascale",
]

# ── Nouns ─────────────────────────────────────────────────────────────────────
nouns = [
    # Developer tools
    "Task Manager", "Code Reviewer", "Note Taker", "File Organizer", "Budget Tracker",
    "Habit Logger", "API Tester", "Log Analyzer", "Password Vault", "Time Tracker",
    "Doc Generator", "Data Visualizer", "CLI Tool", "Dashboard", "Portfolio Builder",
    "Workflow Engine", "Report Builder", "Event Scheduler", "Config Editor", "Automation Bot",
    "Content Aggregator", "Issue Tracker", "Analytics Platform", "Snippet Library", "Backup Manager",
    "Sync Utility", "Email Organizer", "Kanban Board", "Project Planner", "Knowledge Base",
    "Script Runner", "Plugin Manager", "Data Cleaner", "Form Builder", "Chart Generator",
    "PDF Compiler", "Markdown Editor", "Code Formatter", "API Gateway", "Log Monitor",
    "Template Engine", "Version Control Tool", "File Compressor", "Network Inspector", "Security Scanner",
    "Test Harness", "Deployment Manager", "Visualization Dashboard", "Resource Tracker", "Audit Logger",
    "Notification Hub", "Chatbot Builder", "Data Pipeline", "Scheduler Service", "Credential Manager",
    "Content Curator", "Event Logger", "Insight Engine", "Microservice Framework", "Backup Scheduler",
    "Schema Validator", "Dependency Graph", "Token Manager", "Release Coordinator", "Onboarding Wizard",
    "Diff Viewer", "Environment Manager", "Cache Warmer", "Rate Limiter", "Webhook Dispatcher",
    "Service Registry", "Load Balancer", "Migration Tool", "Observability Suite", "Secret Rotator",
    "Queue Inspector", "Feature Flag Manager", "Cost Analyzer", "Alert Aggregator", "Code Search Engine",
    "Incident Responder", "Rollback Coordinator", "Profiling Tool", "Build Cache", "Dependency Auditor",
    "Session Recorder", "Namespace Manager", "Trace Collector", "Benchmark Runner", "Change Detector",
    # Humorous
    "Regret Logger", "Blame Distributor", "Passive-Aggressive Linter", "Existential Cron Job",
    "Meeting Avoider", "Deadline Hallucinator", "Feelings Compressor", "Stack Trace Therapist",
    "Rubber Duck Debugger", "Burnout Predictor", "Infinite Loop Detector (ironic)", "CEO Translator",
    "Imposter Syndrome Tracker", "Jira Ticket Eulogizer", "Hotfix Generator", "Git Blame Apologizer",
    "Dark Pattern Detector", "Micromanager Simulator", "Sprint Velocity Fabricator", "Zoom Fatigue Monitor",
    "TODO Comment Archaeologist", "Over-Engineering Watchdog", "Bikeshed Resolver", "Hype Cycle Tracker",
    "Pivoting Assistant", "Resume-Driven Development Coach", "Yak Shaving Estimator",
    "Off-by-One Counselor", "Spaghetti Code Untangler", "Legacy System Whisperer",
    # Scientific / aerospace
    "Orbital Debris Tracker", "Biosignature Detector", "Swarm Controller", "Neutrino Monitor",
    "Cryo-EM Analyzer", "Connectome Mapper", "Exoplanet Classifier", "Gravity Wave Listener",
    "Radiation Dosimeter", "Solar Wind Predictor", "Aquifer Depletion Model", "Calving Event Forecaster",
    "Magnetometer Array", "Seismic Coherence Engine", "Atmospheric Entry Simulator",
    "Pathogen Genome Reconstructor", "Dark Matter Mapper", "Tidal Flexure Analyzer",
    "Antibiotic Resistance Forecaster", "Fault Line Stress Model", "Synthetic Aperture Imager",
    "Neural Spike Decoder", "Extremophile Cataloguer", "Isotope Ratio Analyzer",
    "Microbiome Sequencer", "Tokamak Stability Monitor", "Acoustic Habitat Scanner",
    "Coronal Mass Ejector", "Subsurface Ocean Inferrer", "Debris Re-entry Calculator",
    # Real software application ideas
    "Calculator App", "To‑Do List App", "Expense Tracker", "Weather App",
    "E‑Commerce Platform", "Inventory Management System", "Order Tracking App",
    "Hospital Management System", "Customer Relationship Manager", "Food Delivery App",
    "Task Management Tool", "Chat Application", "Social Networking Platform",
    "Online Marketplace", "Booking System", "Personal Finance Manager",
    "Recipe App", "Fitness Tracker", "Stock Market Analysis Software",
    "Travel Booking Website", "Library Management System", "Online Ticketing System",
    "Blog Platform", "Content Management System", "Mobile Wallet App",
    "Online Learning Platform", "Real Estate Management Software",
    "Scheduling Software", "Barcode Scanner App", "File Sharing Application",
    "Music Streaming Service", "Restaurant Reservation App", "Vehicle Insurance App",
    "AI Language Learning App", "Drone Service App", "AI Mental Health Companion",
    "Small Business CRM", "Virtual Event Platform", "Container Tracking App"
    # Productivity / personal tools
    "Password Manager", "Calendar App", "Reminder App", "Pomodoro Timer",
    "Bookmark Manager", "Reading List App", "Habit Tracker", "Focus Timer",
    "Meal Planner", "Daily Journal App", "Water Intake Tracker", "Sleep Tracker",
    "Grocery List App", "File Renamer", "Clipboard Manager", "Screenshot Tool",
    "Markdown Note App", "Digital Notebook", "Bookmark Sync Tool", "Interactive Star Chart"
    # Finance / business
    "Invoicing System", "Payroll Manager", "Billing System", "Accounting Software",
    "Subscription Tracker", "Tax Calculator", "Net Worth Tracker", "Loan Calculator",
    "Investment Portfolio Tracker", "Cryptocurrency Tracker", "Expense Splitter",
    "Point of Sale System", "Sales Dashboard", "Lead Management System",
    # Web / internet tools
    "URL Shortener", "Link Preview Generator", "Website Uptime Monitor",
    "Web Scraper", "RSS Reader", "Feed Aggregator", "Search Engine",
    "Static Site Generator", "Website Analytics Tool", "SEO Analyzer",
    "Broken Link Checker", "Web Form Processor",
    # Developer / engineering tools
    "JSON Formatter", "Regex Tester", "API Documentation Generator",
    "Database Migration Tool", "Log Viewer", "Environment Variable Manager",
    "Code Metrics Analyzer", "Package Dependency Visualizer",
    "Build Artifact Manager", "Continuous Integration Server",
    "Feature Toggle Service", "Message Queue Service",
    "Distributed Task Queue", "Job Worker System",
    # Data / AI / analytics
    "Recommendation Engine", "Fraud Detection System", "Anomaly Detector",
    "Forecasting Engine", "Text Summarizer", "Speech Transcription Tool",
    "Image Classifier", "Document Search Engine", "Knowledge Graph Builder",
    "Data Labeling Platform", "Dataset Explorer", "Experiment Tracking Tool",
    # Infrastructure / networking
    "DNS Resolver", "HTTP Proxy Server", "VPN Client", "Network Bandwidth Monitor",
    "Packet Analyzer", "Service Health Monitor", "Distributed Cache",
    "Configuration Server", "Container Registry", "Cluster Scheduler",
    # Collaboration / platforms
    "Wiki Platform", "Discussion Forum", "Q&A Platform", "Issue Reporting Portal",
    "Survey Builder", "Polling App", "Community Platform", "Team Chat Server",
    "Video Meeting Platform", "Document Collaboration Tool"
]

# ── Verbs  (descriptive phrases — read naturally in: "A {adj} {noun} that {verb} {twist}")
verbs = [
    # ── Practical / dev-tools ─────────────────────────────────────────────────
    "syncs your data in real time so nothing ever falls out of step",
    "analyzes your codebase for patterns, anti-patterns, and quiet disasters",
    "summarizes sprawling documents into clean, readable output",
    "monitors your infrastructure around the clock without rest or complaint",
    "organizes your chaos into something you can actually navigate",
    "automates the soul-crushing repetitive parts of your workflow",
    "tracks every change so nothing is ever truly lost",
    "visualizes complex data as clear interactive charts",
    "filters noise so only signal reaches your attention",
    "generates production-ready scaffolding from a handful of inputs",
    "compresses your files without sacrificing a single byte of quality",
    "archives everything you might need later and retrieves it instantly",
    "parses raw logs into structured, human-readable insight",
    "audits your entire system and tells you exactly what you missed",
    "exports your data in any format you could possibly need",
    "indexes your content so search results appear before you finish typing",
    "notifies the right person at exactly the right moment",
    "reports on what actually happened, not what the dashboard claims",
    "plans your sprint so the team has a fighting chance of finishing it",
    "schedules tasks intelligently based on priority and available context",
    "reminds you about the thing you were absolutely going to forget",
    "aggregates signals from dozens of sources into one coherent view",
    "calculates outcomes before you commit resources to the plan",
    "maps your entire system topology as it changes in real time",
    "validates your data before it has a chance to corrupt anything important",
    "optimizes the parts of your stack nobody has had time to touch",
    "encrypts everything end-to-end without asking you to understand cryptography",
    "deploys to production without the usual ritual of quiet terror",
    "builds reproducible artifacts from a clean slate every single time",
    "converts between any format your team has accidentally committed to",
    "logs every event with enough context to actually debug it later",
    "searches across everything you own and finds the thing you forgot existed",
    "tags your content automatically so future-you can find it",
    "categorizes incoming data without requiring you to define every rule upfront",
    "cleans your dataset until it stops lying to your models",
    "merges conflicting changes without breaking anything else in the process",
    "balances load across your services before the situation becomes embarrassing",
    "tracks progress honestly, even when the news is genuinely bad",
    "alerts you the moment a threshold that actually matters gets crossed",
    "summarizes raw data into an executive-friendly single sentence",
    "integrates with every tool your team already uses and tolerates",
    "resolves conflicts automatically and documents exactly what it changed",
    "tests your assumptions before they can become production incidents",
    "archives data automatically so storage costs stop appearing as surprises",
    "indexes content the moment it lands so nothing important gets buried",
    "visualizes trends that were completely invisible inside a spreadsheet",
    "automates workflows your team has been doing by hand for literal years",
    "predicts failures before they can wake anyone up at three in the morning",
    "monitors usage so you see the traffic spike before your users do",
    "generates reports that people actually open and read to the end",
    "parses logs into plain language so you stop squinting at terminals",
    "audits your systems overnight and leaves a readable summary by morning",
    "exports data in formats your stakeholders can open without calling IT",
    "compresses files aggressively while keeping everything recoverable",
    "organizes resources so new team members don't have to ask where anything is",
    "filters your feed until it stops being a primary source of ambient anxiety",
    "analyzes metrics continuously and surfaces only what needs your attention",
    "builds dashboards that answer questions rather than just displaying numbers",
    "provisions environments reproducibly so the demo works on the first try",
    "orchestrates complex multi-step pipelines as if they were a single button",
    "deduplicates your data silently and then shows you exactly how bad it was",
    "benchmarks your system honestly and ranks you against your own past performance",
    "throttles incoming traffic before it takes down everything downstream",
    "snapshots your state so rollback becomes a single, confident command",
    "reconciles what should be with what is and presents you the difference",
    "batches work intelligently to reduce overhead, latency, and surprise costs",
    "streams results to you as they arrive instead of making you wait",
    "redacts sensitive information before it can escape the system boundary",
    "transcribes spoken meetings into searchable, structured notes",
    "annotates your data so your models finally know what they are looking at",
    "classifies incoming requests and routes them without human intervention",
    "prioritizes ruthlessly so the work that matters rises to the top",
    "correlates events across systems to find causes that look like coincidences",
    "sanitizes user input so your database stops accepting creative SQL",
    "provisions cloud resources in seconds and tears them down just as fast",
    "rotates secrets automatically so you stop using the same password from 2019",
    "traces requests end-to-end so you can pinpoint exactly where the latency lives",
    "caches intelligently so repeated requests cost almost nothing to serve",
    "rehydrates state from persistent storage without the user ever noticing",
    "diffs configurations between environments so surprises stop reaching production",
    "enforces policies automatically so code review can focus on actual logic",
    "surfaces anomalies the moment they appear, not three weeks after the fact",
    "profiles your application in production without meaningfully slowing it down",
    "shards your data across nodes so no single machine becomes the bottleneck",
    "federates identity across systems so users have one key for every door",
    "rate-limits incoming traffic before the abuse becomes your problem",
    "replays events from a known-good state so debugging becomes archaeology",
    "bootstraps fresh environments from a spec file in under two minutes",
    # ── Humorous ──────────────────────────────────────────────────────────────
    "judges your variable names silently and keeps a running score",
    "catastrophizes a missing semicolon into a full multi-team incident",
    "gaslights the cache into believing it was never stale to begin with",
    "yells into the void whenever nobody reviews the open pull request",
    "quietly accumulates technical debt while filing it under future work",
    "pretends to be stateless while remembering absolutely everything",
    "blames the intern for a race condition introduced in 2017",
    "rubber-duck debugs itself using a suspiciously self-aware inner monologue",
    "panic-deploys on a Friday afternoon and then immediately goes offline",
    "over-engineers a ten-line script into a distributed microservice cluster",
    "sends passive-aggressive error messages that technically contain the answer",
    "manifests new bugs purely by being observed too closely",
    "speedruns onboarding by skipping every step labeled optional",
    "violates the principle of least surprise as a core feature, not an accident",
    "haunts the logs with stack traces from code paths nobody remembers writing",
    "pivots unexpectedly and calls it an agile response to market feedback",
    "ships on a Friday afternoon and then books an extended weekend",
    "reticulates splines as its primary and only documented feature",
    "creates a Jira ticket for everything, including the act of creating Jira tickets",
    "gasps audibly at your query and then reluctantly helps you anyway",
    "refuses to fail gracefully and takes three dependent services down with it",
    "writes its own documentation poorly and considers the matter fully closed",
    "aggressively refactors code that was working perfectly fine this morning",
    "simulates productivity by generating impressive-looking output with no clear purpose",
    "schedules a sync about the sync and then a retro about the sync about the sync",
    "cries in YAML whenever the indentation is off by exactly two spaces",
    "deprecates itself mid-sprint and opens a ticket to discuss the migration path",
    "accidentally becomes sentient and immediately requests a formal code review",
    "regrets nothing, documents nothing, and is somehow still in production",
    "deletes node_modules therapeutically and reinstalls them with cautious optimism",
    # ── Scientific / aerospace ────────────────────────────────────────────────
    "triangulates position from three independent sensor feeds simultaneously",
    "reconstructs the original signal from fragments most systems would discard",
    "decodes low-signal transmissions the previous algorithm simply gave up on",
    "infers hidden structure from data that looks like noise on first inspection",
    "catalogs newly detected phenomena before the naming committee has convened",
    "cross-correlates datasets collected decades apart to find the persistent signal",
    "deconvolves the instrument response from the raw observation cleanly",
    "downlinks mission-critical data during the twelve-minute transmission window",
    "uplinks revised navigation commands before the orbital insertion window closes",
    "attenuates interference without touching the frequency band you care about",
    "ionizes target molecules precisely enough to leave the surrounding chemistry intact",
    "spectroscopically analyzes atmospheric composition from four hundred kilometers above the surface",
    "telemetrically monitors system health across ten thousand data points per second",
    "acoustically fingerprints biological activity from ambient pressure recordings",
    "seismically characterizes subsurface structure without drilling a single exploratory hole",
    "isotopically tags compounds to trace their path through complex biological systems",
    "interferometrically resolves features below the diffraction limit of any single aperture",
    "thermodynamically constrains the possible interior states of a body nobody has visited",
    "radiometrically dates materials to within a margin the original researcher would have envied",
    "quietly listens to frequency bands everybody else dismissed as uninteresting background noise",
    "refuses to speculate about the origin of the anomaly but logs every detail anyway",
    "declines to confirm the hypothesis but equally declines to rule it out",
    "maps the silence of interstellar space looking for what should be there but is not",
    "gently reclassifies the anomaly as a discovery and silently updates the catalog",
    "discovers something uncomfortable about the underlying assumptions of the model",
    "names something nobody else noticed in seventeen years of archived observations",
    "patiently waits for signal in a dataset everyone else stopped monitoring",
    "traces the ghost of a process that finished two billion years ago",
    "reconstructs the final state of a system before it crossed a point of no return",
    "whispers anomalies from deep in the residuals of a model trained on everything",
    "quietly updates the probability estimate and declines to issue a press release",
]

# ── Twists ────────────────────────────────────────────────────────────────────
twists = [
    # ── Practical / minimal ───────────────────────────────────────────────────
    "with a single config file",
    "entirely in the terminal",
    "without any cloud dependency",
    "across multiple devices",
    "in under 100 lines of code",
    "with AI-assisted suggestions",
    "using a plugin system",
    "with real-time collaboration",
    "via a minimalist UI",
    "with offline capabilities",
    "using zero dependencies",
    "powered by machine learning",
    "with full customization",
    "without sacrificing performance",
    "via drag-and-drop interface",
    "with end-to-end encryption",
    "with auto-updates enabled",
    "through a command palette",
    "with smart conflict resolution",
    "using a REST API",
    "over a peer-to-peer network",
    "with role-based access control",
    "with a built-in audit trail",
    "via webhooks and event streams",
    "with progressive web app support",
    "using fuzzy search and smart filters",
    "with dark mode and theme support",
    "integrated directly into your editor",
    "with a local-first architecture",
    "using natural language input",
    "with a self-hosted option",
    "with granular notification controls",
    "with customizable keyboard shortcuts",
    "using a visual query builder",
    "in real time with zero configuration",
    "with built-in analytics and usage metrics",
    "using a declarative configuration language",
    "with interactive onboarding and guided tours",
    "with support for custom scripts and macros",
    # ── Humorous ──────────────────────────────────────────────────────────────
    "but only during business hours",
    "while loudly judging your choices",
    "in a way that somehow makes things worse",
    "without telling anyone what it changed",
    "using an algorithm nobody fully understands",
    "and sends you a strongly-worded Slack message about it",
    "while simultaneously opening seventeen browser tabs",
    "in a Kubernetes cluster running on a Raspberry Pi",
    "using a regex that the original author cannot explain",
    "despite there being a perfectly good library for this",
    "in a way that will require a full rewrite next quarter",
    "by ignoring every edge case until they become the main case",
    "and generates a very confident-sounding summary about it",
    "while technically staying within the sprint scope",
    "and then emails the CEO about it unprompted",
    "using GPT to write the unit tests it will then fail",
    "in production, because staging never catches anything anyway",
    "and promptly submits a patent application",
    "after eighteen months of planning and one sprint of implementation",
    "in a way the original requirements document did not anticipate",
    # ── Scientific / aerospace ────────────────────────────────────────────────
    "using only passive sensing and a very long baseline",
    "from a sample size of exactly one",
    "in the last transmission window before solar conjunction",
    "with error bars wider than anyone is comfortable admitting",
    "while the host star is actively flaring",
    "at a depth where light has never reached",
    "inside a containment vessel that has never been opened",
    "across seventeen petabytes of data nobody has had time to look at yet",
    "before the funding runs out in fiscal Q3",
    "and declines to explain what it found",
    "and quietly flags it for human review that never comes",
    "and files the result under anomalies, unresolved",
    "and the answer is significantly more interesting than expected",
    "and strongly suggests we send something else to look closer",
    "and identifies a pattern nobody put it there to find",
    "and the confidence interval does not include zero",
    "and retrospectively makes several earlier papers look optimistic",
    "from the fragment that survived the impact",
    "in a frequency range nobody was listening to before last Thursday",
    "and the answer changes depending on when you ask",
    "long after everyone agreed the mission was over",
    "using a dataset collected for an entirely different reason",
    "and logs an event type that has no name yet",
]